#pragma once

#define EASYWG_VERSION_MAJOR 0
#define EASYWG_VERSION_MINOR 2
#define EASYWG_VERSION_PATCH 9
#define EASYWG_VERSION_BUILD 2

#define EASYWG_VERSION_STRING_A "0.2.9.2"
#define EASYWG_VERSION_STRING_W L"0.2.9.2"
#define EASYWG_VERSION_DISPLAY_A "v0.2.9.2"
#define EASYWG_VERSION_DISPLAY_W L"v0.2.9.2"
